language: python

sudo: required

services:
  - docker

install:
  - pip install requests simplejson 
  - make docker
  - make run

script:
  - make tests
  - make log
  - make stop

after_success:
  - sh .travis/deploy.sh
  - sh .travis/deploy_heroku.sh
